### ISSUE TITLE
* provider.template: version = "~> 0.1"

### ISSUE THREAD

**Issue by ozbillwang** [terraform-providers/terraform-provider-template#15]
Hi there,

### Terraform Version
0.10.0

### Affected Resource(s)
- provider.template

### Terraform Configuration Files
```hcl
data "template_file" "init" {
  template = "${file("init.tpl")}"

  vars {
    consul_address = "${aws_instance.consul.private_ip}"
  }
}
```

### Debug Output

```
terraform init -backend-config=config/backend.conf

Initializing the backend...

Initializing provider plugins...
- Downloading plugin for provider "template"...
- Downloading plugin for provider "aws"...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 0.1"
* provider.template: version = "~> 0.1"

Terraform has been successfully initialized!

...
```

### Questions

I have to guess how to set provider template version and below codes work in fact. 

```
provider "template" {
  version = "~> 0.1"
}
```

Can anyone confirm if this is the right way to lock provider `template` version? If it is, I can raise PR to update in README. 

### Updates:
Seems provider `template` doesn't support key `region`. 

     * provider.template: : invalid or unknown key: region

**Comment by radeksimko** [comment]
Hi @ozbillwang 
the syntax for provider version constraints is documented at https://www.terraform.io/docs/configuration/providers.html#provider-versions
Is there any other place where you'd expect this to find? It is certainly a provider-agnostic topic, so I'd refrain from documenting it at provider-level, unless it's just a brief explanation w/ link to something more generic.

> Seems provider template doesn't support key region.

That's correct. Do you mind explaining why should `template` provider support `region` key? Template provider's responsibility is merely to do templating without calling any external provider which would require a region.

**Comment by ozbillwang** [comment]
Thanks, @radeksimko 

If I'd like to know the keys for provider `template`, where can I get the details?

**Comment by radeksimko** [comment]
@ozbillwang There is no configuration necessary for the `template` provider. There may be optional meta-fields like this `version` one, but there's nothing `template` specific.

There is one other meta field called `alias` which is documented at https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances
