### ISSUE TITLE
Breaking change in substitution in v2.0.0

### ISSUE THREAD

**Issue by krk** [terraform-providers/terraform-provider-template#52]
In v1.0.0, `$$(a)` is replaced to `$(a)` whereas v2.0.0 keeps the original.

To test, add the following test cases to https://github.com/terraform-providers/terraform-provider-template/blob/05c8f40512b96b2009f0ad4369f3634b3cddbb6f/template/datasource_template_file_test.go#L17

```go
{`{a="foo"}`, `$$(a)`, `$$(a)`},
{`{a="foo"}`, `$(a)`, `$(a)`},
```

It passes in v2.0.0 but fails in v1.0.0

**Comment by apparentlymart** [comment]
Hi @krk,

This seems to be the same as #49, so I'm going to close this just to consolidate the discussion. Please see the comments there to either constrain your provider version to the 1.0 release or to remove this redundant escaping.
