### ISSUE TITLE
template_dir doesn't work on Terraform v0.12.4

### ISSUE THREAD

**Issue by navi86** [terraform-providers/terraform-provider-template#66]
Hi there,

### Terraform Version
Terraform v0.12.4

### Affected Resource(s)
+ provider.template v2.1.2

I am trying to render template's folder using the following documentation:
https://www.terraform.io/docs/providers/template/r/dir.html

### Expected Behavior
Rendered templates were created

### Actual Behavior
got error `The provider provider.template does not support data source "template_dir".`

### Steps to Reproduce
1. `terraform apply`

**Comment by ekini** [comment]
Can you show the actual code? https://www.terraform.io/docs/providers/template/r/dir.html is a resource, not data.

**Comment by navi86** [comment]
sorry, it was my fault, everything is working.

**Comment by navi86** [comment]
sorry, it was my fault, everything is working.
