### ISSUE TITLE
[regression] provider-template fails rendering when template file has % in the content starting from v2.0.0

### ISSUE THREAD

**Issue by amgohan** [terraform-providers/terraform-provider-template#69]
Hi there,

### Terraform Version
terraform version : 0.11.14

### Affected Resource(s)
- template_file since v2.0.0

#### main.tf
```hcl
data "template_file" "file" {
  template = "${file("${path.module}/file.tpl")}"
  vars = {
    name = "foo"
  }
}

output "rendered_file" {
  value = "${data.template_file.file.rendered}"
}
```

#### file.tpl
```
hello ${name},
%{bar}
```

### Debug Output
```
data.template_file.file: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.template_file.file: 1 error(s) occurred:

* data.template_file.file: data.template_file.file: failed to render : <template_file>:2,3-6: Invalid template control keyword; "bar" is not a valid template control keyword. Did you mean "for"?
```

### Expected Behavior
The apply should render the `data.template_file.file.rendered` value correctly as follows:
```
rendered_file = hello foo,
%{bar}
```

### Actual Behavior
generating an error using terraform-provider-template v2.0.0 and above, but working fine in v1.0.0
`* data.template_file.file: data.template_file.file: failed to render : <template_file>:2,3-6: Invalid template control keyword; "bar" is not a valid template control keyword. Did you mean "for"?`

### Steps to Reproduce
1. `terraform init && terraform apply`

**Comment by mikecook** [comment]
https://github.com/terraform-providers/terraform-provider-template/blob/master/CHANGELOG.md#200-january-14-2019
```HCL 2.0 template syntax includes a new %{ ... } construct for control structures, like %{ if a == b } ... %{ endif }. If your existing templates contain any %{ sequences you will need to now escape them as %%{ to ensure correct parsing.```

**Comment by mildwonkey** [comment]
Hi! @mikecook has it right - in the provider v2.0 and later you need to escape `%` with as `%%`. Thanks!

**Comment by amgohan** [comment]
Thanks, my problem is solved. I didn't notice that in the Changelog.
